var LIVEGREP_STORAGE_KEY = "LIVEGREP_STORAGE_KEY";
var RECENT_SEARCHES_DELIMITER = ",";

module.exports = {
  LIVEGREP_STORAGE_KEY: LIVEGREP_STORAGE_KEY,
  RECENT_SEARCHES_DELIMITER: RECENT_SEARCHES_DELIMITER
}