package(default_visibility = ['//visibility:public'])

load('@org_dropbox_rules_node//node:defs.bzl', 'node_internal_module')

node_internal_module(
    name = 'internal_module',
    srcs = ['internal_module.js'],
    main = 'internal_module.js',
)
