#!/home/nelhage/sw/bin/node

var fs    = require('fs'),
path  = require('path');

var stats = path.join(__dirname, '..', 'web', 'log', 'stats.json');

if (process.argv[2] === 'config') {
  console.log("graph_title Codesearch qps");
  console.log("graph_vlabel Queries/sec");
  console.log("graph_category Codesearch");
  console.log("graph_scale no");
  console.log("fast.label Fast QPS");
  console.log("slow.label Slow QPS");
  process.exit(0);
}

var data;
try {
  data = JSON.parse(fs.readFileSync(stats, 'utf8'));
} catch(e) {
  process.stderr.write("No data file found.\n");
  process.exit(1)
}

console.log("slow.value %d", data.slow.qps);
console.log("fast.value %d", data.fast.qps);
