load(
    "@io_bazel_rules_go//go:def.bzl",
    "go_library",
)

go_library(
    name = "go_default_library",
    srcs = ["jsonframe.go"],
    importpath = "github.com/livegrep/livegrep/jsonframe",
    visibility = ["//visibility:public"],
)
