
load("@io_bazel_rules_go//go:def.bzl",
  "go_binary",
  "go_library",
  "go_test",
)

go_library(
name = "go_default_library",
  srcs = [
    "jsonframe.go",
  ],
  deps = [
  ],
  visibility = ["//visibility:public"],
)


